name: Deploy to Netlify

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Deploy
        run: curl -X POST -d {} "${{ secrets.NETLIFY_HOOK }}"
